import java.util.LinkedList;
import java.util.List;

/* The following code was generated by JFlex 1.6.1 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/herre/Universidad/TFG/Pruebas/lexicojf.flex</tt>
 */
class Lexicojf {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int DECL = 2;
  public static final int AUX = 4;
  public static final int REGEXP = 6;
  public static final int REGLEX = 8;
  public static final int ERAUX = 10;
  public static final int ESTAUX = 12;
  public static final int ESTAUX2 = 14;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7, 7
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\7\1\2\1\5\1\5\1\1\22\0\1\10\4\0\1\12"+
    "\4\0\1\4\4\0\1\3\12\6\2\0\1\26\1\24\3\0\32\6"+
    "\6\0\4\6\1\16\1\20\1\6\1\21\1\13\4\6\1\14\1\17"+
    "\2\6\1\22\1\6\1\15\2\6\1\23\3\6\1\11\1\0\1\25"+
    "\7\0\1\5\u1fa2\0\1\5\1\5\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\10\0\6\1\1\2\1\3\2\1\1\4\2\3\2\5"+
    "\2\6\1\7\1\0\1\10\2\0\1\11\4\0\1\3"+
    "\2\0\1\3\1\5\1\6\2\7\2\0\1\12\10\0"+
    "\2\3\2\5\2\6\5\0\1\13\1\0\1\7\1\13"+
    "\1\3\1\7\1\5\1\7\1\6\1\7\12\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\27\0\56\0\105\0\134\0\163\0\212\0\241"+
    "\0\270\0\317\0\346\0\375\0\u0114\0\u012b\0\u0142\0\u0159"+
    "\0\u0170\0\u0187\0\270\0\u019e\0\u01b5\0\u01cc\0\u01e3\0\u01fa"+
    "\0\u0211\0\u0228\0\u023f\0\270\0\375\0\u0256\0\270\0\u026d"+
    "\0\u0284\0\u029b\0\u02b2\0\270\0\u02c9\0\u02e0\0\u02f7\0\u030e"+
    "\0\u0325\0\u033c\0\270\0\u0353\0\u036a\0\270\0\u0381\0\u0398"+
    "\0\u03af\0\u03c6\0\u03dd\0\u03f4\0\u040b\0\u0422\0\u0439\0\u0450"+
    "\0\u0467\0\u047e\0\u0495\0\u04ac\0\u04c3\0\u04da\0\u04f1\0\u0508"+
    "\0\u051f\0\u02c9\0\u0536\0\u02c9\0\u03f4\0\u054d\0\u019e\0\u0564"+
    "\0\u01cc\0\u057b\0\u01fa\0\u0592\0\u05a9\0\u05c0\0\u05d7\0\u05ee"+
    "\0\u0605\0\u061c\0\u0633\0\u064a\0\u0661";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\3\11\1\12\6\11\1\13\17\11\1\12\2\11\1\14"+
    "\3\11\1\15\11\14\6\11\1\12\6\11\1\16\17\11"+
    "\1\12\2\11\1\14\1\11\1\17\1\11\1\20\11\14"+
    "\3\11\1\21\2\11\1\22\3\21\2\11\15\21\1\23"+
    "\1\24\2\11\1\25\1\24\1\11\21\24\1\26\2\11"+
    "\1\27\1\26\1\11\21\26\1\30\2\11\1\31\1\30"+
    "\1\11\21\30\32\0\1\32\1\33\34\0\1\34\22\0"+
    "\1\35\1\0\1\36\2\0\11\35\14\0\1\37\1\0"+
    "\1\40\2\0\1\41\23\0\1\42\2\0\1\43\6\0"+
    "\1\34\11\0\1\17\30\0\1\44\14\0\1\45\2\0"+
    "\2\45\1\0\22\45\2\0\1\32\1\46\1\0\21\45"+
    "\1\24\2\0\2\24\1\0\22\24\2\0\1\32\1\47"+
    "\1\0\21\24\1\26\2\0\2\26\1\0\22\26\2\0"+
    "\1\32\1\50\1\0\21\26\1\30\2\0\2\30\1\0"+
    "\22\30\2\0\1\32\1\51\1\0\21\30\1\32\1\52"+
    "\1\53\24\32\4\54\1\55\22\54\10\0\1\36\13\0"+
    "\1\56\16\0\1\57\31\0\1\60\23\0\1\61\31\0"+
    "\1\62\7\0\1\45\2\0\2\45\1\0\2\45\1\63"+
    "\16\45\1\64\2\54\1\64\1\65\1\54\2\64\1\66"+
    "\16\64\1\67\2\54\1\67\1\70\1\54\21\67\1\71"+
    "\2\54\1\71\1\72\1\54\21\71\1\73\2\54\1\73"+
    "\1\74\1\54\21\73\2\0\1\53\24\0\4\54\1\75"+
    "\22\54\3\0\1\53\1\55\35\0\1\76\33\0\1\77"+
    "\21\0\1\100\33\0\1\101\6\0\1\45\2\0\2\45"+
    "\1\0\2\45\1\63\1\102\15\45\1\64\2\54\1\64"+
    "\1\103\1\54\2\64\1\66\16\64\1\45\2\0\1\104"+
    "\1\65\1\0\2\45\1\63\16\45\1\64\2\54\1\64"+
    "\1\103\1\54\2\64\1\66\1\105\15\64\1\67\2\54"+
    "\1\67\1\106\1\54\21\67\1\24\2\0\1\107\1\70"+
    "\1\0\21\24\1\71\2\54\1\71\1\110\1\54\21\71"+
    "\1\26\2\0\1\111\1\72\1\0\21\26\1\73\2\54"+
    "\1\73\1\112\1\54\21\73\1\30\2\0\1\113\1\74"+
    "\1\0\21\30\3\54\1\53\1\75\22\54\15\0\1\114"+
    "\22\0\1\37\32\0\1\115\36\0\1\34\1\0\1\64"+
    "\2\54\1\104\1\103\1\54\2\64\1\66\16\64\1\67"+
    "\2\54\1\107\1\106\1\54\21\67\1\71\2\54\1\111"+
    "\1\110\1\54\21\71\1\73\2\54\1\113\1\112\1\54"+
    "\21\73\11\0\1\37\3\0\1\116\26\0\1\117\7\0"+
    "\1\34\22\0\1\120\26\0\1\121\27\0\1\122\26\0"+
    "\1\123\23\0\1\124\26\0\1\125\32\0\1\77\26\0"+
    "\1\101\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1656];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\10\0\1\11\11\1\1\11\7\1\1\0\1\11\2\0"+
    "\1\11\4\0\1\11\2\0\4\1\1\11\2\0\1\11"+
    "\10\0\6\1\5\0\1\1\1\0\10\1\12\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[85];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  List<String> regexList = new LinkedList<>(); // Lista para guardar las expresiones regulares
  List<String> macrosList = new LinkedList<>(); // Lista para guardar las macros asociadas a las expresiones regulares


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexicojf(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 124) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
	int mem = -1; // Variable auxiliar mia
	String cad = ""; // Variable auxiliar mia
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { ;
            }
          case 12: break;
          case 2: 
            { yybegin(ESTAUX2);
            }
          case 13: break;
          case 3: 
            { yybegin(REGLEX);
            }
          case 14: break;
          case 4: 
            { yybegin(ERAUX);
            }
          case 15: break;
          case 5: 
            { 
            	regexList.add(yytext());
            	mem++;
						 yybegin(REGEXP);
            }
          case 16: break;
          case 6: 
            { 
            	cad = regexList.get(mem);
            	regexList.remove(mem);
            	cad = cad + yytext();
            	regexList.add(mem, cad);
						 yybegin(REGEXP);
            }
          case 17: break;
          case 7: 
            { /*Sin accion*/
            }
          case 18: break;
          case 8: 
            { yybegin(DECL);
            }
          case 19: break;
          case 9: 
            { yybegin(AUX);
            }
          case 20: break;
          case 10: 
            { 
            	macrosList.add(yytext());
						 yybegin(ESTAUX);
            }
          case 21: break;
          case 11: 
            { 
            	regexList.add(yytext());
						 yybegin(ERAUX);
            }
          case 22: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }
}
