
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import say.swing.JFontChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author herre
 */
public class P_ajustes extends javax.swing.JDialog {

    private List<Font> l_fuentes = new LinkedList<>();
    private List<Font> l_fuentes_mod = new LinkedList<>();
    private List<Color> l_colores = new LinkedList<>();
    private List<Color> l_colores_mod = new LinkedList<>();
    /**
     * Creates new form P_ajustes
     * @param parent
     * @param modal
     * @param lf
     * @param lc
     */
    public P_ajustes(java.awt.Frame parent, boolean modal, List<Font> lf, List<Color> lc) {
        super(parent, modal);
        this.l_fuentes.addAll(lf);
        this.l_colores.addAll(lc);
        this.l_fuentes_mod.addAll(lf);
        this.l_colores_mod.addAll(lc);
        initComponents();
        this.setLocationRelativeTo(null);
        
        ImageIcon helpImage = new ImageIcon(getClass().getResource(("/Imágenes/help.png")));
        Icon iconHelp = new ImageIcon(helpImage.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        this.jLabel4.setIcon(iconHelp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txFuente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btFuente = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btColorFuente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btColorFondo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        lbFuente = new javax.swing.JLabel();
        lbColorFuente = new javax.swing.JLabel();
        lbColorFondo = new javax.swing.JLabel();
        txColorFuente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txColorFondo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbFuente2 = new javax.swing.JLabel();
        lbColorFuente2 = new javax.swing.JLabel();
        lbColorFondo2 = new javax.swing.JLabel();
        txColorFuente2 = new javax.swing.JTextField();
        txFuente1 = new javax.swing.JTextField();
        txColorFondo2 = new javax.swing.JTextField();
        btFuente2 = new javax.swing.JButton();
        btColorFuente2 = new javax.swing.JButton();
        btColorFondo2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajustes");

        txFuente.setEditable(false);
        txFuente.setFocusable(false);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btFuente.setText("...");
        btFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuenteActionPerformed(evt);
            }
        });

        jButton3.setText("Aplicar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btColorFuente.setText("...");
        btColorFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorFuenteActionPerformed(evt);
            }
        });

        btColorFondo.setText("...");
        btColorFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorFondoActionPerformed(evt);
            }
        });

        jLabel4.setText("Ayuda");

        jLabel1.setText("Componentes de texto del área de espresiones regulares:");

        jLabel2.setText("Componentes de texto de la cadena de entrada:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Definiciones Regulares/Patrones activos", "Definiciones Regulares/Patrones NO activos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lexemas COMPLETAMENTE detectados en la entrada", "Lexemas NO detectados en la entrada", "Lexemas PARCIALMENTE detectados en la entrada" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList2ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        lbFuente.setText("Fuente:");

        lbColorFuente.setText("Color de fuente:");

        lbColorFondo.setText("Color de fondo:");

        txColorFuente.setEditable(false);
        txColorFuente.setFocusable(false);

        txColorFondo.setEditable(false);
        txColorFondo.setFocusable(false);

        jButton1.setText("Valores por defecto");

        lbFuente2.setText("Fuente:");

        lbColorFuente2.setText("Color de fuente:");

        lbColorFondo2.setText("Color de fondo:");

        txColorFuente2.setEditable(false);
        txColorFuente2.setFocusable(false);

        txFuente1.setEditable(false);
        txFuente1.setFocusable(false);

        txColorFondo2.setEditable(false);
        txColorFondo2.setFocusable(false);

        btFuente2.setText("...");
        btFuente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFuente2ActionPerformed(evt);
            }
        });

        btColorFuente2.setText("...");
        btColorFuente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorFuente2ActionPerformed(evt);
            }
        });

        btColorFondo2.setText("...");
        btColorFondo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorFondo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbColorFuente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbColorFondo)
                                    .addComponent(lbFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txColorFuente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(txFuente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txColorFondo))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btColorFuente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btColorFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbColorFuente2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbColorFondo2)
                                            .addComponent(lbFuente2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txColorFuente2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txFuente1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txColorFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(btFuente2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btColorFuente2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btColorFondo2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFuente)
                            .addComponent(txFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColorFuente)
                            .addComponent(txColorFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btColorFuente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbColorFondo)
                            .addComponent(btColorFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFuente2)
                            .addComponent(txFuente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btFuente2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbColorFuente2)
                            .addComponent(txColorFuente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btColorFuente2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txColorFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbColorFondo2)
                            .addComponent(btColorFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.l_fuentes_mod.clear();
        this.l_colores_mod.clear();
        this.l_fuentes_mod.addAll(l_fuentes);
        this.l_colores_mod.addAll(l_colores);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public List<Font> getL_fuentes_mod() {
        return l_fuentes_mod;
    }

    public List<Color> getL_colores_mod() {
        return l_colores_mod;
    }

    private void btFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuenteActionPerformed
        int i, res;
        if (this.jList1.getSelectedValue().equals("Definiciones Regulares/Patrones activos")) {
            i = 0;
        } else {
            i = 1;
        }
        JFontChooser jf = new JFontChooser();
        res = jf.showDialog(null);
        if (res == JFontChooser.OK_OPTION) {
            Font f = jf.getSelectedFont();
            this.l_fuentes_mod.set(i, f);
            this.txFuente.setText(this.l_fuentes_mod.get(i).getName() + " " + this.l_fuentes_mod.get(i).getSize());
        }
    }//GEN-LAST:event_btFuenteActionPerformed

    private void btColorFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColorFuenteActionPerformed
        int i;
        if (this.jList1.getSelectedValue().equals("Definiciones Regulares/Patrones activos")) {
            i = 0;
        } else {
            i = 2;
        }
        Color c = JColorChooser.showDialog(null, "Selecciona un color", this.l_colores_mod.get(i));
        if (c!= null) {
            this.l_colores_mod.set(i, c);
            this.txColorFuente.setText(this.l_colores_mod.get(i).getRed() + ", " + this.l_colores_mod.get(i).getGreen() + ", " + this.l_colores_mod.get(i).getBlue());
        }
    }//GEN-LAST:event_btColorFuenteActionPerformed

    private void btColorFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColorFondoActionPerformed
        int i;
        if (this.jList1.getSelectedValue().equals("Definiciones Regulares/Patrones activos")) {
            i = 1;
        } else {
            i = 3;
        }
        Color c = JColorChooser.showDialog(null, "Selecciona un color", this.l_colores_mod.get(i));
        if (c!= null) {
            this.l_colores_mod.set(i, c);
            this.txColorFondo.setText(this.l_colores_mod.get(i).getRed() + ", " + this.l_colores_mod.get(i).getGreen() + ", " + this.l_colores_mod.get(i).getBlue());
        }
    }//GEN-LAST:event_btColorFondoActionPerformed

    private void btFuente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFuente2ActionPerformed
        int i, res;
        switch (this.jList2.getSelectedValue()) {
            case "Lexemas COMPLETAMENTE detectados en la entrada":
                i = 2;
                break;
            case "Lexemas NO detectados en la entrada":
                i = 3;
                break;
            default:
                i = 4;
                break;
        }
        JFontChooser jf = new JFontChooser();
        res = jf.showDialog(null);
        if (res == JFontChooser.OK_OPTION) {
            Font f = jf.getSelectedFont();
            this.l_fuentes_mod.set(i, f);
            this.txFuente1.setText(this.l_fuentes_mod.get(i).getName() + " " + this.l_fuentes_mod.get(i).getSize());
        }
    }//GEN-LAST:event_btFuente2ActionPerformed

    private void btColorFuente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColorFuente2ActionPerformed
        int i;
        switch (this.jList2.getSelectedValue()) {
            case "Lexemas COMPLETAMENTE detectados en la entrada":
                i = 4;
                break;
            case "Lexemas NO detectados en la entrada":
                i = 6;
                break;
            default:
                i = 8;
                break;
        }
        Color c = JColorChooser.showDialog(null, "Selecciona un color", this.l_colores_mod.get(i));
        if (c!= null) {
            this.l_colores_mod.set(i, c);
            this.txColorFuente2.setText(this.l_colores_mod.get(i).getRed() + ", " + this.l_colores_mod.get(i).getGreen() + ", " + this.l_colores_mod.get(i).getBlue());
        }
    }//GEN-LAST:event_btColorFuente2ActionPerformed

    private void btColorFondo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColorFondo2ActionPerformed
        int i;
        switch (this.jList2.getSelectedValue()) {
            case "Lexemas COMPLETAMENTE detectados en la entrada":
                i = 5;
                break;
            case "Lexemas NO detectados en la entrada":
                i = 7;
                break;
            default:
                i = 9;
                break;
        }
        Color c = JColorChooser.showDialog(null, "Selecciona un color", this.l_colores_mod.get(i));
        if (c!= null) {
            this.l_colores_mod.set(i, c);
            this.txColorFondo2.setText(this.l_colores_mod.get(i).getRed() + ", " + this.l_colores_mod.get(i).getGreen() + ", " + this.l_colores_mod.get(i).getBlue());
        }
    }//GEN-LAST:event_btColorFondo2ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (this.jList1.getSelectedValue().equals("Definiciones Regulares/Patrones activos")) {
            this.txFuente.setText(this.l_fuentes_mod.get(0).getName() + " " + this.l_fuentes_mod.get(0).getSize());
            this.txColorFuente.setText(this.l_colores_mod.get(0).getRed() + ", " + this.l_colores_mod.get(0).getGreen() + ", " + this.l_colores_mod.get(0).getBlue());
            this.txColorFondo.setText(this.l_colores_mod.get(1).getRed() + ", " + this.l_colores_mod.get(1).getGreen() + ", " + this.l_colores_mod.get(1).getBlue());
        } else {
            this.txFuente.setText(this.l_fuentes_mod.get(1).getName() + " " + this.l_fuentes_mod.get(1).getSize());
            this.txColorFuente.setText(this.l_colores_mod.get(2).getRed() + ", " + this.l_colores_mod.get(2).getGreen() + ", " + this.l_colores_mod.get(2).getBlue());
            this.txColorFondo.setText(this.l_colores_mod.get(3).getRed() + ", " + this.l_colores_mod.get(3).getGreen() + ", " + this.l_colores_mod.get(3).getBlue());
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jList2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList2ValueChanged
        switch (this.jList2.getSelectedValue()) {
            case "Lexemas COMPLETAMENTE detectados en la entrada":
                txFuente1.setText(this.l_fuentes_mod.get(2).getName() + " " + this.l_fuentes_mod.get(2).getSize());
                this.txColorFuente2.setText(this.l_colores_mod.get(4).getRed() + ", " + this.l_colores_mod.get(4).getGreen() + ", " + this.l_colores_mod.get(4).getBlue());
                this.txColorFondo2.setText(this.l_colores_mod.get(5).getRed() + ", " + this.l_colores_mod.get(5).getGreen() + ", " + this.l_colores_mod.get(5).getBlue());
                break;
            case "Lexemas NO detectados en la entrada":
                txFuente1.setText(this.l_fuentes_mod.get(3).getName() + " " + this.l_fuentes_mod.get(3).getSize());
                this.txColorFuente2.setText(this.l_colores_mod.get(6).getRed() + ", " + this.l_colores_mod.get(6).getGreen() + ", " + this.l_colores_mod.get(6).getBlue());
                this.txColorFondo2.setText(this.l_colores_mod.get(7).getRed() + ", " + this.l_colores_mod.get(7).getGreen() + ", " + this.l_colores_mod.get(7).getBlue());
                break;
            default:
                txFuente1.setText(this.l_fuentes_mod.get(4).getName() + " " + this.l_fuentes_mod.get(4).getSize());
                this.txColorFuente2.setText(this.l_colores_mod.get(8).getRed() + ", " + this.l_colores_mod.get(8).getGreen() + ", " + this.l_colores_mod.get(8).getBlue());
                this.txColorFondo2.setText(this.l_colores_mod.get(9).getRed() + ", " + this.l_colores_mod.get(9).getGreen() + ", " + this.l_colores_mod.get(9).getBlue());
                break;
        }
    }//GEN-LAST:event_jList2ValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btColorFondo;
    private javax.swing.JButton btColorFondo2;
    private javax.swing.JButton btColorFuente;
    private javax.swing.JButton btColorFuente2;
    private javax.swing.JButton btFuente;
    private javax.swing.JButton btFuente2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbColorFondo;
    private javax.swing.JLabel lbColorFondo2;
    private javax.swing.JLabel lbColorFuente;
    private javax.swing.JLabel lbColorFuente2;
    private javax.swing.JLabel lbFuente;
    private javax.swing.JLabel lbFuente2;
    private javax.swing.JTextField txColorFondo;
    private javax.swing.JTextField txColorFondo2;
    private javax.swing.JTextField txColorFuente;
    private javax.swing.JTextField txColorFuente2;
    private javax.swing.JTextField txFuente;
    private javax.swing.JTextField txFuente1;
    // End of variables declaration//GEN-END:variables
}
