
import java.awt.Color;
import java.awt.Font;
import static java.awt.Font.BOLD;
import static java.awt.Font.PLAIN;
import java.awt.Image;
import java.util.LinkedList;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import say.swing.JFontChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author herre
 */
public class P_ajustes extends javax.swing.JDialog {

    private List<Font> l_fuentes = new LinkedList<>();
    private List<Font> l_fuentes_mod = new LinkedList<>();
    private List<Font> l_fuentes_def = new LinkedList<>();
    private List<Color> l_colores_def = new LinkedList<>();
    private List<Color> l_colores = new LinkedList<>();
    private List<Color> l_colores_mod = new LinkedList<>();
    /**
     * Creates new form P_ajustes
     * @param parent
     * @param modal
     * @param lf
     * @param lc
     */
    public P_ajustes(java.awt.Frame parent, boolean modal, List<Font> lf, List<Color> lc) {
        super(parent, modal);
        this.l_fuentes.addAll(lf);
        this.l_colores.addAll(lc);
        this.l_fuentes_mod.addAll(lf);
        this.l_colores_mod.addAll(lc);
        
        // Seteamos los colores y las fuentes por defecto
        this.l_fuentes_def.add(new Font("Tahoma",BOLD,18)); // Fuente ACTIVADAS
        this.l_colores_def.add(new Color(106,90,205)); // Color de fuente ACTIVADAS
        this.l_colores_def.add(Color.WHITE); // Color de fondo de fuente ACTIVADAS
        
        this.l_fuentes_def.add(new Font("Tahoma",PLAIN,16)); // Fuente NO ACTIVADAS
        this.l_colores_def.add(new Color(109,109,109));
        this.l_colores_def.add(Color.WHITE);
        
        this.l_fuentes_def.add(new Font("Tahoma",BOLD,18)); // Fuente COMPLETAS
        this.l_colores_def.add(Color.BLACK); // Color de fuente COMPLETAS
        this.l_colores_def.add(Color.WHITE); // Color de fondo de fuente COMPLETAS
        
        this.l_fuentes_def.add(new Font("Verdana",BOLD,18)); // Fuente entrada COMPLETA
        this.l_colores_def.add(Color.WHITE);
        this.l_colores_def.add(new Color(25,25,112));
        
        this.l_fuentes_def.add(new Font("Verdana",BOLD,18)); // Fuente entrada NO activada ni completa
        this.l_colores_def.add(new Color(109,109,109));
        this.l_colores_def.add(Color.WHITE);
        
        this.l_fuentes_def.add(new Font("Verdana",BOLD,18)); // Fuente entrada ACTIVADA
        this.l_colores_def.add(new Color(109,109,109));
        this.l_colores_def.add(new Color(173,216,230));
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        ImageIcon helpImage = new ImageIcon(getClass().getResource(("/Imágenes/help.png")));
        Icon iconHelp = new ImageIcon(helpImage.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        this.lb_ayuda.setIcon(iconHelp);
        
        this.tx_fuente_1.setText(this.l_fuentes_mod.get(0).getName() + " " + this.l_fuentes_mod.get(0).getSize());
        this.tx_color_fuente_1.setText(this.l_colores_mod.get(0).getRed() + ", " + this.l_colores_mod.get(0).getGreen() + ", " + this.l_colores_mod.get(0).getBlue());
        this.tx_color_fondo_1.setText(this.l_colores_mod.get(1).getRed() + ", " + this.l_colores_mod.get(1).getGreen() + ", " + this.l_colores_mod.get(1).getBlue());
        
        this.tx_fuente_2.setText(this.l_fuentes_mod.get(3).getName() + " " + this.l_fuentes_mod.get(3).getSize());
        this.tx_color_fuente_2.setText(this.l_colores_mod.get(6).getRed() + ", " + this.l_colores_mod.get(6).getGreen() + ", " + this.l_colores_mod.get(6).getBlue());
        this.tx_color_fondo_2.setText(this.l_colores_mod.get(7).getRed() + ", " + this.l_colores_mod.get(7).getGreen() + ", " + this.l_colores_mod.get(7).getBlue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tx_fuente_1 = new javax.swing.JTextField();
        boton_cancelar = new javax.swing.JButton();
        boton_fuente_1 = new javax.swing.JButton();
        boton_aplicar = new javax.swing.JButton();
        boton_color_fuente_1 = new javax.swing.JButton();
        Separador_2 = new javax.swing.JSeparator();
        boton_color_fondo_1 = new javax.swing.JButton();
        lb_ayuda = new javax.swing.JLabel();
        lb_titulo_1 = new javax.swing.JLabel();
        lb_titulo_2 = new javax.swing.JLabel();
        scroll_lista_1 = new javax.swing.JScrollPane();
        lista_1 = new javax.swing.JList<>();
        scroll_lista_2 = new javax.swing.JScrollPane();
        lista_2 = new javax.swing.JList<>();
        lb_fuente_1 = new javax.swing.JLabel();
        lb_color_fuente_1 = new javax.swing.JLabel();
        lb_color_fondo_1 = new javax.swing.JLabel();
        tx_color_fuente_1 = new javax.swing.JTextField();
        separador_1 = new javax.swing.JSeparator();
        tx_color_fondo_1 = new javax.swing.JTextField();
        boton_defecto = new javax.swing.JButton();
        lb_fuente_2 = new javax.swing.JLabel();
        lb_color_fuente_2 = new javax.swing.JLabel();
        lb_color_fondo_2 = new javax.swing.JLabel();
        tx_color_fuente_2 = new javax.swing.JTextField();
        tx_fuente_2 = new javax.swing.JTextField();
        tx_color_fondo_2 = new javax.swing.JTextField();
        boton_fuente_2 = new javax.swing.JButton();
        boton_color_fuente_2 = new javax.swing.JButton();
        boton_color_fondo_2 = new javax.swing.JButton();
        boton_reestablecer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        setTitle(bundle.getString("P_ajustes.title")); // NOI18N

        tx_fuente_1.setEditable(false);
        tx_fuente_1.setFocusable(false);

        boton_cancelar.setText(bundle.getString("P_ajustes.boton_cancelar.text")); // NOI18N
        boton_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cancelarActionPerformed(evt);
            }
        });

        boton_fuente_1.setText(bundle.getString("P_ajustes.boton_fuente_1.text")); // NOI18N
        boton_fuente_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_fuente_1ActionPerformed(evt);
            }
        });

        boton_aplicar.setText(bundle.getString("P_ajustes.boton_aplicar.text")); // NOI18N
        boton_aplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aplicarActionPerformed(evt);
            }
        });

        boton_color_fuente_1.setText(bundle.getString("P_ajustes.boton_color_fuente_1.text")); // NOI18N
        boton_color_fuente_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_color_fuente_1ActionPerformed(evt);
            }
        });

        boton_color_fondo_1.setText(bundle.getString("P_ajustes.boton_color_fondo_1.text")); // NOI18N
        boton_color_fondo_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_color_fondo_1ActionPerformed(evt);
            }
        });

        lb_ayuda.setText(bundle.getString("P_ajustes.lb_ayuda.text")); // NOI18N

        lb_titulo_1.setText(bundle.getString("P_ajustes.lb_titulo_1.text")); // NOI18N

        lb_titulo_2.setText(bundle.getString("P_ajustes.lb_titulo_2.text")); // NOI18N

        lista_1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Definiciones Regulares/Patrones activos", "Definiciones Regulares/Patrones NO activos", "Definiciones Regulares/Patrones completos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_1.setSelectedIndex(0);
        lista_1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_1ValueChanged(evt);
            }
        });
        scroll_lista_1.setViewportView(lista_1);

        lista_2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lexemas COMPLETAMENTE detectados en la entrada", "Lexemas NO detectados en la entrada", "Lexemas PARCIALMENTE detectados en la entrada" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista_2.setSelectedIndex(0);
        lista_2.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista_2ValueChanged(evt);
            }
        });
        scroll_lista_2.setViewportView(lista_2);

        lb_fuente_1.setText(bundle.getString("P_ajustes.lb_fuente_1.text")); // NOI18N

        lb_color_fuente_1.setText(bundle.getString("P_ajustes.lb_color_fuente_1.text")); // NOI18N

        lb_color_fondo_1.setText(bundle.getString("P_ajustes.lb_color_fondo_1.text")); // NOI18N

        tx_color_fuente_1.setEditable(false);
        tx_color_fuente_1.setFocusable(false);

        tx_color_fondo_1.setEditable(false);
        tx_color_fondo_1.setFocusable(false);

        boton_defecto.setText(bundle.getString("P_ajustes.boton_defecto.text")); // NOI18N
        boton_defecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_defectoActionPerformed(evt);
            }
        });

        lb_fuente_2.setText(bundle.getString("P_ajustes.lb_fuente_2.text")); // NOI18N

        lb_color_fuente_2.setText(bundle.getString("P_ajustes.lb_color_fuente_2.text")); // NOI18N

        lb_color_fondo_2.setText(bundle.getString("P_ajustes.lb_color_fondo_2.text")); // NOI18N

        tx_color_fuente_2.setEditable(false);
        tx_color_fuente_2.setFocusable(false);

        tx_fuente_2.setEditable(false);
        tx_fuente_2.setFocusable(false);

        tx_color_fondo_2.setEditable(false);
        tx_color_fondo_2.setFocusable(false);

        boton_fuente_2.setText(bundle.getString("P_ajustes.boton_fuente_2.text")); // NOI18N
        boton_fuente_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_fuente_2ActionPerformed(evt);
            }
        });

        boton_color_fuente_2.setText(bundle.getString("P_ajustes.boton_color_fuente_2.text")); // NOI18N
        boton_color_fuente_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_color_fuente_2ActionPerformed(evt);
            }
        });

        boton_color_fondo_2.setText(bundle.getString("P_ajustes.boton_color_fondo_2.text")); // NOI18N
        boton_color_fondo_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_color_fondo_2ActionPerformed(evt);
            }
        });

        boton_reestablecer.setText(bundle.getString("P_ajustes.boton_reestablecer.text")); // NOI18N
        boton_reestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_reestablecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lb_ayuda))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Separador_2)
                            .addComponent(separador_1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(scroll_lista_1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_color_fuente_1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_color_fondo_1)
                                    .addComponent(lb_fuente_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tx_color_fuente_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(tx_fuente_1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tx_color_fondo_1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(boton_fuente_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boton_color_fuente_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(boton_color_fondo_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(scroll_lista_2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boton_defecto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(boton_aplicar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton_cancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton_reestablecer))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lb_color_fuente_2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lb_color_fondo_2)
                                            .addComponent(lb_fuente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tx_color_fuente_2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tx_fuente_2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tx_color_fondo_2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(boton_fuente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(boton_color_fuente_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(boton_color_fondo_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_titulo_1)
                                    .addComponent(lb_titulo_2))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_ayuda)
                .addGap(7, 7, 7)
                .addComponent(lb_titulo_1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scroll_lista_1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_fuente_1)
                            .addComponent(tx_fuente_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_fuente_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_color_fuente_1)
                            .addComponent(tx_color_fuente_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_color_fuente_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_color_fondo_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_color_fondo_1)
                            .addComponent(boton_color_fondo_1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addComponent(separador_1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_titulo_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_lista_2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_fuente_2)
                            .addComponent(tx_fuente_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_fuente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_color_fuente_2)
                            .addComponent(tx_color_fuente_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_color_fuente_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tx_color_fondo_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_color_fondo_2)
                            .addComponent(boton_color_fondo_2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(Separador_2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_defecto)
                    .addComponent(boton_cancelar)
                    .addComponent(boton_aplicar)
                    .addComponent(boton_reestablecer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cancelarActionPerformed
        this.l_fuentes_mod.clear();
        this.l_colores_mod.clear();
        this.l_fuentes_mod.addAll(l_fuentes);
        this.l_colores_mod.addAll(l_colores);
        this.dispose();
    }//GEN-LAST:event_boton_cancelarActionPerformed

    public List<Font> getL_fuentes_mod() {
        return l_fuentes_mod;
    }

    public List<Color> getL_colores_mod() {
        return l_colores_mod;
    }

    private void boton_fuente_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_fuente_1ActionPerformed
        int i, res;
        if (!this.lista_1.isSelectionEmpty()) {
            switch (this.lista_1.getSelectedValue()) {
                case "Definiciones Regulares/Patrones activos":
                    i = 0;
                    break;
                case "Definiciones Regulares/Patrones NO activos":
                    i = 1;
                    break;
                default:
                    i = 2;
                    break;
            }
            JFontChooser jf = new JFontChooser();
            res = jf.showDialog(null);
            if (res == JFontChooser.OK_OPTION) {
                Font f = jf.getSelectedFont();
                this.l_fuentes_mod.set(i, f);
                this.tx_fuente_1.setText(this.l_fuentes_mod.get(i).getName() + " " + this.l_fuentes_mod.get(i).getSize());
            }
        }
    }//GEN-LAST:event_boton_fuente_1ActionPerformed

    private void boton_color_fuente_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_color_fuente_1ActionPerformed
        int i;
        if (!this.lista_1.isSelectionEmpty()) {
            switch (this.lista_1.getSelectedValue()) {
                case "Definiciones Regulares/Patrones activos":
                    i = 0;
                    break;
                case "Definiciones Regulares/Patrones NO activos":
                    i = 2;
                    break;
                default:
                    i = 4;
                    break;
            }
            Color c = JColorChooser.showDialog(null, "Selecciona un color", this.l_colores_mod.get(i));
            if (c!= null) {
                this.l_colores_mod.set(i, c);
                this.tx_color_fuente_1.setText(this.l_colores_mod.get(i).getRed() + ", " + this.l_colores_mod.get(i).getGreen() + ", " + this.l_colores_mod.get(i).getBlue());
            }
        }
    }//GEN-LAST:event_boton_color_fuente_1ActionPerformed

    private void boton_color_fondo_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_color_fondo_1ActionPerformed
        int i;
        if (!this.lista_1.isSelectionEmpty()) {
            switch (this.lista_1.getSelectedValue()) {
                case "Definiciones Regulares/Patrones activos":
                    i = 1;
                    break;
                case "Definiciones Regulares/Patrones NO activos":
                    i = 3;
                    break;
                default:
                    i = 5;
                    break;
            }
            Color c = JColorChooser.showDialog(null, "Selecciona un color", this.l_colores_mod.get(i));
            if (c!= null) {
                this.l_colores_mod.set(i, c);
                this.tx_color_fondo_1.setText(this.l_colores_mod.get(i).getRed() + ", " + this.l_colores_mod.get(i).getGreen() + ", " + this.l_colores_mod.get(i).getBlue());
            }
        }
    }//GEN-LAST:event_boton_color_fondo_1ActionPerformed

    private void boton_fuente_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_fuente_2ActionPerformed
        int i, res;
        if (!this.lista_2.isSelectionEmpty()) {
            switch (this.lista_2.getSelectedValue()) {
                case "Lexemas COMPLETAMENTE detectados en la entrada":
                    i = 3;
                    break;
                case "Lexemas NO detectados en la entrada":
                    i = 4;
                    break;
                default:
                    i = 5;
                    break;
            }
            JFontChooser jf = new JFontChooser();
            res = jf.showDialog(null);
            if (res == JFontChooser.OK_OPTION) {
                Font f = jf.getSelectedFont();
                this.l_fuentes_mod.set(i, f);
                this.tx_fuente_2.setText(this.l_fuentes_mod.get(i).getName() + " " + this.l_fuentes_mod.get(i).getSize());
            }
        }
    }//GEN-LAST:event_boton_fuente_2ActionPerformed

    private void boton_color_fuente_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_color_fuente_2ActionPerformed
        int i;
        if (!this.lista_2.isSelectionEmpty()) {
            switch (this.lista_2.getSelectedValue()) {
                case "Lexemas COMPLETAMENTE detectados en la entrada":
                    i = 6;
                    break;
                case "Lexemas NO detectados en la entrada":
                    i = 8;
                    break;
                default:
                    i = 10;
                    break;
            }
            Color c = JColorChooser.showDialog(null, "Selecciona un color", this.l_colores_mod.get(i));
            if (c!= null) {
                this.l_colores_mod.set(i, c);
                this.tx_color_fuente_2.setText(this.l_colores_mod.get(i).getRed() + ", " + this.l_colores_mod.get(i).getGreen() + ", " + this.l_colores_mod.get(i).getBlue());
            }
        }
    }//GEN-LAST:event_boton_color_fuente_2ActionPerformed

    private void boton_color_fondo_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_color_fondo_2ActionPerformed
        int i;
        if (!this.lista_2.isSelectionEmpty()) {
            switch (this.lista_2.getSelectedValue()) {
                case "Lexemas COMPLETAMENTE detectados en la entrada":
                    i = 7;
                    break;
                case "Lexemas NO detectados en la entrada":
                    i = 9;
                    break;
                default:
                    i = 11;
                    break;
            }
            Color c = JColorChooser.showDialog(null, "Selecciona un color", this.l_colores_mod.get(i));
            if (c!= null) {
                this.l_colores_mod.set(i, c);
                this.tx_color_fondo_2.setText(this.l_colores_mod.get(i).getRed() + ", " + this.l_colores_mod.get(i).getGreen() + ", " + this.l_colores_mod.get(i).getBlue());
            }
        }
    }//GEN-LAST:event_boton_color_fondo_2ActionPerformed

    private void lista_1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_1ValueChanged
        switch (this.lista_1.getSelectedValue()) {
            case "Definiciones Regulares/Patrones activos":
                this.tx_fuente_1.setText(this.l_fuentes_mod.get(0).getName() + " " + this.l_fuentes_mod.get(0).getSize());
                this.tx_color_fuente_1.setText(this.l_colores_mod.get(0).getRed() + ", " + this.l_colores_mod.get(0).getGreen() + ", " + this.l_colores_mod.get(0).getBlue());
                this.tx_color_fondo_1.setText(this.l_colores_mod.get(1).getRed() + ", " + this.l_colores_mod.get(1).getGreen() + ", " + this.l_colores_mod.get(1).getBlue());
                break;
            case "Definiciones Regulares/Patrones NO activos":
                this.tx_fuente_1.setText(this.l_fuentes_mod.get(1).getName() + " " + this.l_fuentes_mod.get(1).getSize());
                this.tx_color_fuente_1.setText(this.l_colores_mod.get(2).getRed() + ", " + this.l_colores_mod.get(2).getGreen() + ", " + this.l_colores_mod.get(2).getBlue());
                this.tx_color_fondo_1.setText(this.l_colores_mod.get(3).getRed() + ", " + this.l_colores_mod.get(3).getGreen() + ", " + this.l_colores_mod.get(3).getBlue());
                break;
            default:
                this.tx_fuente_1.setText(this.l_fuentes_mod.get(2).getName() + " " + this.l_fuentes_mod.get(2).getSize());
                this.tx_color_fuente_1.setText(this.l_colores_mod.get(4).getRed() + ", " + this.l_colores_mod.get(4).getGreen() + ", " + this.l_colores_mod.get(4).getBlue());
                this.tx_color_fondo_1.setText(this.l_colores_mod.get(5).getRed() + ", " + this.l_colores_mod.get(5).getGreen() + ", " + this.l_colores_mod.get(5).getBlue());
                break;
        }
    }//GEN-LAST:event_lista_1ValueChanged

    private void lista_2ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista_2ValueChanged
        switch (this.lista_2.getSelectedValue()) {
            case "Lexemas COMPLETAMENTE detectados en la entrada":
                tx_fuente_2.setText(this.l_fuentes_mod.get(3).getName() + " " + this.l_fuentes_mod.get(3).getSize());
                this.tx_color_fuente_2.setText(this.l_colores_mod.get(6).getRed() + ", " + this.l_colores_mod.get(6).getGreen() + ", " + this.l_colores_mod.get(6).getBlue());
                this.tx_color_fondo_2.setText(this.l_colores_mod.get(7).getRed() + ", " + this.l_colores_mod.get(7).getGreen() + ", " + this.l_colores_mod.get(7).getBlue());
                break;
            case "Lexemas NO detectados en la entrada":
                tx_fuente_2.setText(this.l_fuentes_mod.get(4).getName() + " " + this.l_fuentes_mod.get(4).getSize());
                this.tx_color_fuente_2.setText(this.l_colores_mod.get(8).getRed() + ", " + this.l_colores_mod.get(8).getGreen() + ", " + this.l_colores_mod.get(8).getBlue());
                this.tx_color_fondo_2.setText(this.l_colores_mod.get(9).getRed() + ", " + this.l_colores_mod.get(9).getGreen() + ", " + this.l_colores_mod.get(9).getBlue());
                break;
            default:
                tx_fuente_2.setText(this.l_fuentes_mod.get(5).getName() + " " + this.l_fuentes_mod.get(5).getSize());
                this.tx_color_fuente_2.setText(this.l_colores_mod.get(10).getRed() + ", " + this.l_colores_mod.get(10).getGreen() + ", " + this.l_colores_mod.get(10).getBlue());
                this.tx_color_fondo_2.setText(this.l_colores_mod.get(11).getRed() + ", " + this.l_colores_mod.get(11).getGreen() + ", " + this.l_colores_mod.get(11).getBlue());
                break;
        }
    }//GEN-LAST:event_lista_2ValueChanged

    private void boton_aplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aplicarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de aplicar los valores actuales?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
            this.dispose();
            JOptionPane.showMessageDialog(null, "¡Valores cambiados con éxito!", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_boton_aplicarActionPerformed

    private void boton_defectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_defectoActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de cambiar a los valores por defecto?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) { 
            this.l_fuentes_mod.clear();
            this.l_fuentes_mod.addAll(l_fuentes_def);
            this.l_colores_mod.clear();
            this.l_colores_mod.addAll(l_colores_def);

            if (!this.lista_1.isSelectionEmpty()) {
                switch (this.lista_1.getSelectedValue()) {
                    case "Definiciones Regulares/Patrones activos":
                        this.tx_fuente_1.setText(this.l_fuentes_mod.get(0).getName() + " " + this.l_fuentes_mod.get(0).getSize());
                        this.tx_color_fuente_1.setText(this.l_colores_mod.get(0).getRed() + ", " + this.l_colores_mod.get(0).getGreen() + ", " + this.l_colores_mod.get(0).getBlue());
                        this.tx_color_fondo_1.setText(this.l_colores_mod.get(1).getRed() + ", " + this.l_colores_mod.get(1).getGreen() + ", " + this.l_colores_mod.get(1).getBlue());
                        break;
                    case "Definiciones Regulares/Patrones NO activos":
                        this.tx_fuente_1.setText(this.l_fuentes_mod.get(1).getName() + " " + this.l_fuentes_mod.get(1).getSize());
                        this.tx_color_fuente_1.setText(this.l_colores_mod.get(2).getRed() + ", " + this.l_colores_mod.get(2).getGreen() + ", " + this.l_colores_mod.get(2).getBlue());
                        this.tx_color_fondo_1.setText(this.l_colores_mod.get(3).getRed() + ", " + this.l_colores_mod.get(3).getGreen() + ", " + this.l_colores_mod.get(3).getBlue());
                        break;
                    default:
                        this.tx_fuente_1.setText(this.l_fuentes_mod.get(2).getName() + " " + this.l_fuentes_mod.get(2).getSize());
                        this.tx_color_fuente_1.setText(this.l_colores_mod.get(4).getRed() + ", " + this.l_colores_mod.get(4).getGreen() + ", " + this.l_colores_mod.get(4).getBlue());
                        this.tx_color_fondo_1.setText(this.l_colores_mod.get(5).getRed() + ", " + this.l_colores_mod.get(5).getGreen() + ", " + this.l_colores_mod.get(5).getBlue());
                        break;
                }
            }

            if (!this.lista_2.isSelectionEmpty()) {
                switch (this.lista_2.getSelectedValue()) {
                    case "Lexemas COMPLETAMENTE detectados en la entrada":
                        tx_fuente_2.setText(this.l_fuentes_mod.get(3).getName() + " " + this.l_fuentes_mod.get(3).getSize());
                        this.tx_color_fuente_2.setText(this.l_colores_mod.get(6).getRed() + ", " + this.l_colores_mod.get(6).getGreen() + ", " + this.l_colores_mod.get(6).getBlue());
                        this.tx_color_fondo_2.setText(this.l_colores_mod.get(7).getRed() + ", " + this.l_colores_mod.get(7).getGreen() + ", " + this.l_colores_mod.get(7).getBlue());
                        break;
                    case "Lexemas NO detectados en la entrada":
                        tx_fuente_2.setText(this.l_fuentes_mod.get(4).getName() + " " + this.l_fuentes_mod.get(4).getSize());
                        this.tx_color_fuente_2.setText(this.l_colores_mod.get(8).getRed() + ", " + this.l_colores_mod.get(8).getGreen() + ", " + this.l_colores_mod.get(8).getBlue());
                        this.tx_color_fondo_2.setText(this.l_colores_mod.get(9).getRed() + ", " + this.l_colores_mod.get(9).getGreen() + ", " + this.l_colores_mod.get(9).getBlue());
                        break;
                    default:
                        tx_fuente_2.setText(this.l_fuentes_mod.get(5).getName() + " " + this.l_fuentes_mod.get(5).getSize());
                        this.tx_color_fuente_2.setText(this.l_colores_mod.get(10).getRed() + ", " + this.l_colores_mod.get(10).getGreen() + ", " + this.l_colores_mod.get(10).getBlue());
                        this.tx_color_fondo_2.setText(this.l_colores_mod.get(11).getRed() + ", " + this.l_colores_mod.get(11).getGreen() + ", " + this.l_colores_mod.get(11).getBlue());
                        break;
                }
            }
        }
    }//GEN-LAST:event_boton_defectoActionPerformed

    private void boton_reestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_reestablecerActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de reestablecer los valores?", "Advertencia", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) { 
            this.l_fuentes_mod.clear();
            this.l_fuentes_mod.addAll(l_fuentes);
            this.l_colores_mod.clear();
            this.l_colores_mod.addAll(l_colores);

            if (!this.lista_1.isSelectionEmpty()) {
                switch (this.lista_1.getSelectedValue()) {
                    case "Definiciones Regulares/Patrones activos":
                        this.tx_fuente_1.setText(this.l_fuentes_mod.get(0).getName() + " " + this.l_fuentes_mod.get(0).getSize());
                        this.tx_color_fuente_1.setText(this.l_colores_mod.get(0).getRed() + ", " + this.l_colores_mod.get(0).getGreen() + ", " + this.l_colores_mod.get(0).getBlue());
                        this.tx_color_fondo_1.setText(this.l_colores_mod.get(1).getRed() + ", " + this.l_colores_mod.get(1).getGreen() + ", " + this.l_colores_mod.get(1).getBlue());
                        break;
                    case "Definiciones Regulares/Patrones NO activos":
                        this.tx_fuente_1.setText(this.l_fuentes_mod.get(1).getName() + " " + this.l_fuentes_mod.get(1).getSize());
                        this.tx_color_fuente_1.setText(this.l_colores_mod.get(2).getRed() + ", " + this.l_colores_mod.get(2).getGreen() + ", " + this.l_colores_mod.get(2).getBlue());
                        this.tx_color_fondo_1.setText(this.l_colores_mod.get(3).getRed() + ", " + this.l_colores_mod.get(3).getGreen() + ", " + this.l_colores_mod.get(3).getBlue());
                        break;
                    default:
                        this.tx_fuente_1.setText(this.l_fuentes_mod.get(2).getName() + " " + this.l_fuentes_mod.get(2).getSize());
                        this.tx_color_fuente_1.setText(this.l_colores_mod.get(4).getRed() + ", " + this.l_colores_mod.get(4).getGreen() + ", " + this.l_colores_mod.get(4).getBlue());
                        this.tx_color_fondo_1.setText(this.l_colores_mod.get(5).getRed() + ", " + this.l_colores_mod.get(5).getGreen() + ", " + this.l_colores_mod.get(5).getBlue());
                        break;
                }
            }

            if (!this.lista_2.isSelectionEmpty()) {
                switch (this.lista_2.getSelectedValue()) {
                    case "Lexemas COMPLETAMENTE detectados en la entrada":
                        tx_fuente_2.setText(this.l_fuentes_mod.get(3).getName() + " " + this.l_fuentes_mod.get(3).getSize());
                        this.tx_color_fuente_2.setText(this.l_colores_mod.get(6).getRed() + ", " + this.l_colores_mod.get(6).getGreen() + ", " + this.l_colores_mod.get(4).getBlue());
                        this.tx_color_fondo_2.setText(this.l_colores_mod.get(7).getRed() + ", " + this.l_colores_mod.get(7).getGreen() + ", " + this.l_colores_mod.get(5).getBlue());
                        break;
                    case "Lexemas NO detectados en la entrada":
                        tx_fuente_2.setText(this.l_fuentes_mod.get(4).getName() + " " + this.l_fuentes_mod.get(4).getSize());
                        this.tx_color_fuente_2.setText(this.l_colores_mod.get(8).getRed() + ", " + this.l_colores_mod.get(8).getGreen() + ", " + this.l_colores_mod.get(8).getBlue());
                        this.tx_color_fondo_2.setText(this.l_colores_mod.get(9).getRed() + ", " + this.l_colores_mod.get(9).getGreen() + ", " + this.l_colores_mod.get(9).getBlue());
                        break;
                    default:
                        tx_fuente_2.setText(this.l_fuentes_mod.get(5).getName() + " " + this.l_fuentes_mod.get(5).getSize());
                        this.tx_color_fuente_2.setText(this.l_colores_mod.get(10).getRed() + ", " + this.l_colores_mod.get(10).getGreen() + ", " + this.l_colores_mod.get(10).getBlue());
                        this.tx_color_fondo_2.setText(this.l_colores_mod.get(11).getRed() + ", " + this.l_colores_mod.get(11).getGreen() + ", " + this.l_colores_mod.get(11).getBlue());
                        break;
                }
            }
        }
    }//GEN-LAST:event_boton_reestablecerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separador_2;
    private javax.swing.JButton boton_aplicar;
    private javax.swing.JButton boton_cancelar;
    private javax.swing.JButton boton_color_fondo_1;
    private javax.swing.JButton boton_color_fondo_2;
    private javax.swing.JButton boton_color_fuente_1;
    private javax.swing.JButton boton_color_fuente_2;
    private javax.swing.JButton boton_defecto;
    private javax.swing.JButton boton_fuente_1;
    private javax.swing.JButton boton_fuente_2;
    private javax.swing.JButton boton_reestablecer;
    private javax.swing.JLabel lb_ayuda;
    private javax.swing.JLabel lb_color_fondo_1;
    private javax.swing.JLabel lb_color_fondo_2;
    private javax.swing.JLabel lb_color_fuente_1;
    private javax.swing.JLabel lb_color_fuente_2;
    private javax.swing.JLabel lb_fuente_1;
    private javax.swing.JLabel lb_fuente_2;
    private javax.swing.JLabel lb_titulo_1;
    private javax.swing.JLabel lb_titulo_2;
    private javax.swing.JList<String> lista_1;
    private javax.swing.JList<String> lista_2;
    private javax.swing.JScrollPane scroll_lista_1;
    private javax.swing.JScrollPane scroll_lista_2;
    private javax.swing.JSeparator separador_1;
    private javax.swing.JTextField tx_color_fondo_1;
    private javax.swing.JTextField tx_color_fondo_2;
    private javax.swing.JTextField tx_color_fuente_1;
    private javax.swing.JTextField tx_color_fuente_2;
    private javax.swing.JTextField tx_fuente_1;
    private javax.swing.JTextField tx_fuente_2;
    // End of variables declaration//GEN-END:variables
}
