
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author herre
 */
public class Pantalla extends javax.swing.JFrame {

    private List<String> entrada = new LinkedList<>();
    private List<List<Analizador.Estado>> estadoEntrada = new LinkedList<>();
    private List<String> lER;
    private List<Analizador.Estado> lEaux;
    private List<Analizador.Estado> lE = new LinkedList<>();
    private List<Integer> lnER = new LinkedList<>();
    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecera = new javax.swing.JPanel();
        et_titulo = new javax.swing.JLabel();
        boton_nueva = new javax.swing.JButton();
        scroll_panel_expr = new javax.swing.JScrollPane();
        panel_expr = new javax.swing.JTextPane();
        cabecera_entrada = new javax.swing.JPanel();
        et_entrada = new javax.swing.JLabel();
        scroll_panel_entrada = new javax.swing.JScrollPane();
        panel_entrada = new javax.swing.JTextPane();
        cabecera_esp = new javax.swing.JPanel();
        et_especificacion = new javax.swing.JLabel();
        boton_procesar = new javax.swing.JButton();
        scroll_panel_especificacion = new javax.swing.JScrollPane();
        panel_especificacion = new javax.swing.JTextPane();
        cabecera_act = new javax.swing.JPanel();
        et_act = new javax.swing.JLabel();
        scroll_panel_activadas = new javax.swing.JScrollPane();
        panel_activadas = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        cabecera.setBackground(new java.awt.Color(16, 17, 18));

        et_titulo.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        et_titulo.setForeground(new java.awt.Color(112, 176, 224));
        et_titulo.setText("Detector de patrones");

        boton_nueva.setBackground(new java.awt.Color(51, 51, 51));
        boton_nueva.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        boton_nueva.setForeground(new java.awt.Color(112, 176, 224));
        boton_nueva.setText("Nueva");
        boton_nueva.setBorder(null);
        boton_nueva.setBorderPainted(false);
        boton_nueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nuevaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cabeceraLayout = new javax.swing.GroupLayout(cabecera);
        cabecera.setLayout(cabeceraLayout);
        cabeceraLayout.setHorizontalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabeceraLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(et_titulo)
                .addGap(18, 18, 18)
                .addComponent(boton_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cabeceraLayout.setVerticalGroup(
            cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boton_nueva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(et_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        scroll_panel_expr.setBackground(new java.awt.Color(255, 255, 255));
        scroll_panel_expr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        panel_expr.setEditable(false);
        panel_expr.setBorder(null);
        panel_expr.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        panel_expr.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        panel_expr.setFocusable(false);
        scroll_panel_expr.setViewportView(panel_expr);

        cabecera_entrada.setBackground(new java.awt.Color(112, 176, 224));

        et_entrada.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        et_entrada.setText("Entrada");

        javax.swing.GroupLayout cabecera_entradaLayout = new javax.swing.GroupLayout(cabecera_entrada);
        cabecera_entrada.setLayout(cabecera_entradaLayout);
        cabecera_entradaLayout.setHorizontalGroup(
            cabecera_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecera_entradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(et_entrada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cabecera_entradaLayout.setVerticalGroup(
            cabecera_entradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecera_entradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(et_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        scroll_panel_entrada.setBorder(null);

        panel_entrada.setBorder(null);
        scroll_panel_entrada.setViewportView(panel_entrada);

        cabecera_esp.setBackground(new java.awt.Color(183, 188, 192));

        et_especificacion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        et_especificacion.setText("Especificación léxica");

        boton_procesar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        boton_procesar.setText("Procesar");
        boton_procesar.setBorder(null);
        boton_procesar.setBorderPainted(false);
        boton_procesar.setEnabled(false);
        boton_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_procesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cabecera_espLayout = new javax.swing.GroupLayout(cabecera_esp);
        cabecera_esp.setLayout(cabecera_espLayout);
        cabecera_espLayout.setHorizontalGroup(
            cabecera_espLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecera_espLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(et_especificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cabecera_espLayout.setVerticalGroup(
            cabecera_espLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cabecera_espLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabecera_espLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boton_procesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(et_especificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap())
        );

        scroll_panel_especificacion.setBorder(null);

        panel_especificacion.setEditable(false);
        panel_especificacion.setBorder(null);
        panel_especificacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panel_especificacion.setFocusable(false);
        scroll_panel_especificacion.setViewportView(panel_especificacion);

        cabecera_act.setBackground(new java.awt.Color(183, 188, 192));

        et_act.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        et_act.setText("Expresiones regulares activadas");

        javax.swing.GroupLayout cabecera_actLayout = new javax.swing.GroupLayout(cabecera_act);
        cabecera_act.setLayout(cabecera_actLayout);
        cabecera_actLayout.setHorizontalGroup(
            cabecera_actLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecera_actLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(et_act)
                .addContainerGap(460, Short.MAX_VALUE))
        );
        cabecera_actLayout.setVerticalGroup(
            cabecera_actLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabecera_actLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(et_act, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
        );

        scroll_panel_activadas.setBorder(null);

        panel_activadas.setEditable(false);
        panel_activadas.setBorder(null);
        panel_activadas.setFocusable(false);
        scroll_panel_activadas.setViewportView(panel_activadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scroll_panel_expr, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cabecera_entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scroll_panel_entrada)
                    .addComponent(cabecera_esp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scroll_panel_especificacion)
                    .addComponent(cabecera_act, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(scroll_panel_activadas))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_panel_expr)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cabecera_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(scroll_panel_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cabecera_esp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(scroll_panel_especificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(cabecera_act, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(scroll_panel_activadas, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_nuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nuevaActionPerformed
        String especificacion = null;
        try {
            especificacion = this.abrirArchivo();
        } catch (Exception ex) {
            Logger.getLogger(FPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (especificacion != null)
        {
            this.panel_especificacion.setText(especificacion);
            this.panel_especificacion.setCaretPosition(0);
            this.boton_procesar.setEnabled(true);
            this.panel_expr.setText("");
        }
        else
        {
            // Añadir advertencia de archivo nulo
            this.boton_procesar.setEnabled(false);
        }
    }//GEN-LAST:event_boton_nuevaActionPerformed

    private void boton_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_procesarActionPerformed
        String cad = this.lER.get(0);
        for (int i = 1; i < this.lER.size(); i++)
        {
            cad += "\n" + this.lER.get(i);
        }
        this.panel_expr.setText(cad);
        this.panel_expr.setCaretPosition(0);
        this.boton_procesar.setEnabled(false);
    }//GEN-LAST:event_boton_procesarActionPerformed

    @SuppressWarnings("null")
    private String abrirArchivo() throws Exception {
        String aux;   
        String texto="";
        try
        {
            JFileChooser file=new JFileChooser();
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "Especificación léxica","flex","flex");
            file.setFileFilter(filter);
            file.showOpenDialog(this);
            File abre=file.getSelectedFile();
            lER = Procesador.procesarEsp(abre.getPath());

            if(abre!=null)
            {     
               FileReader archivos=new FileReader(abre);
                try (BufferedReader lee = new BufferedReader(archivos)) {
                    while((aux=lee.readLine())!=null)
                    {
                        texto+= aux+ "\n";
                    }
                }
            }    
        }
        catch(IOException ex)
        {
          JOptionPane.showMessageDialog(null,ex+"" +
                "\nNo se ha encontrado el archivo",
                      "ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
        }
        return texto;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_nueva;
    private javax.swing.JButton boton_procesar;
    private javax.swing.JPanel cabecera;
    private javax.swing.JPanel cabecera_act;
    private javax.swing.JPanel cabecera_entrada;
    private javax.swing.JPanel cabecera_esp;
    private javax.swing.JLabel et_act;
    private javax.swing.JLabel et_entrada;
    private javax.swing.JLabel et_especificacion;
    private javax.swing.JLabel et_titulo;
    private javax.swing.JTextPane panel_activadas;
    private javax.swing.JTextPane panel_entrada;
    private javax.swing.JTextPane panel_especificacion;
    private javax.swing.JTextPane panel_expr;
    private javax.swing.JScrollPane scroll_panel_activadas;
    private javax.swing.JScrollPane scroll_panel_entrada;
    private javax.swing.JScrollPane scroll_panel_especificacion;
    private javax.swing.JScrollPane scroll_panel_expr;
    // End of variables declaration//GEN-END:variables
}
